version: '3'

name: countlet_bot_app

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  discord_bot:
    build: .
    depends_on:
      - postgres_db
      - kafka
    environment:
      CLIENT_TOKEN: $CLIENT_TOKEN
      GUILD_ID: 780312283233779713
      COUNT_CHAN_ID: 1038808890466390066
      SEARCH_AFTER_MSG_ID: 1053012296370229248
      DATABASE_URL: postgres://$DB_USER:$DB_PASSWORD@postgres:5432/countlet_bot

  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: countlet_bot
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data



volumes:
  db-data: