version: '3'

name: countlet_bot_app

services:
  discord_bot:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://$DB_USER:$DB_PASSWORD@postgres:5432/your_database_name
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
