version: '3'

name: countlet_bot_app

services:
  discord_bot:
    build: .
    depends_on:
      - postgres
    environment:
      CLIENT_TOKEN: $CLIENT_TOKEN
      GUILD_ID: 780312283233779713
      COUNT_CHAN_ID: 1038808890466390066
      SEARCH_AFTER_MSG_ID: 1053012296370229248
      DATABASE_URL: postgres://$DB_USER:$DB_PASSWORD@postgres:5432/countlet_bot
    networks:
      - app-network

networks:
  app-network: