postgres:
  image: postgres:latest
  env_file:
    - .env
  environment:
    POSTGRES_USER: $DB_USER
    POSTGRES_PASSWORD: $DB_PASSWORD
    POSTGRES_DB: countlet_bot
  ports:
    - "5432:5432"
  networks:
    - app-network

networks:
app-network: